#!/bin/sh

set -e

this_dir="$(readlink -f "$(dirname "$0")")"

export PATH="$this_dir"/usr/bin:"$PATH"
export LD_LIBRARY_PATH="$this_dir"/usr/lib

cd "$this_dir"
exec lib64/ld-linux-x86-64.so.2 usr/bin/game "$@"
